# Generated by Django 4.0.6 on 2022-07-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
