# Generated by Django 4.0.6 on 2022-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0002_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
    ]
