# Generated by Django 4.0.6 on 2022-07-17 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0003_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
