# Generated by Django 4.0.6 on 2022-07-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0004_alter_transferencia_data_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
